version: '3.9'

services:
  nest-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: nest-redis
    hostname: nest-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
